name: issue-agent
on:
  issues:
    types: [opened, edited, reopened]
permissions:
  contents: write
  pull-requests: write
  issues: read
jobs:
  run-agent:
    if: contains(github.event.issue.labels.*.name, 'agent')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install anthropic pygit2 pyyaml

      - name: Run Agent
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # fallback
          GH_TOKEN: ${{ secrets.GH_PAT }}             # gh CLI öncelikle GH_TOKEN'ı kullanır
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          
          ANTHROPIC_AUTH_TOKEN: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
          ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}
          ANTHROPIC_MODEL: ${{ secrets.ANTHROPIC_MODEL }}
          ANTHROPIC_SMALL_FAST_MODEL: ${{ secrets.ANTHROPIC_SMALL_FAST_MODEL }}
          BASH_DEFAULT_TIMEOUT_MS: ${{ secrets.BASH_DEFAULT_TIMEOUT_MS }}
          BASH_MAX_TIMEOUT_MS: ${{ secrets.BASH_MAX_TIMEOUT_MS }}
          MCP_TIMEOUT: ${{ secrets.MCP_TIMEOUT }}
          MCP_TOOL_TIMEOUT: ${{ secrets.MCP_TOOL_TIMEOUT }}
          
          REPO_FULL: ${{ github.repository }}
        run: python .github/agent/issue_agent.py
