name: issue-agent
on:
  issues:
    types: [opened, edited, reopened]
permissions:
  contents: write
  pull-requests: write
  issues: read
jobs:
  run-agent:
    if: contains(github.event.issue.labels.*.name, 'agent')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install anthropic pygit2 pyyaml

      - name: Run Agent
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_FULL: ${{ github.repository }}
        run: python .github/agent/issue_agent.py
